export const Login = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER'
};

export const Campaign = {
  SET_CURRENT_CAMPAIGN: 'SET_CURRENT_CAMPAIGN',
  UPDATE_CAMPAIGN_LIST: 'UPDATE_CAMPAIGN_LIST',
  CREATING_CAMPAIGN: 'CREATING_CAMPAIGN',
  SET_CAMPAIGN_LIST: 'SET_CAMPAIGN_LIST',
  DELETING_CAMPAIGN: 'DELETING_CAMPAIGN'
};

export const Place = {
  DELETING_PLACE: 'DELETING_PLACE',
  CREATING_PLACE: 'CREATING_PLACE',
  UPDATE_PLACE: 'UPDATE_PLACE',
  UPDATE_PLACE_LIST: 'UPDATE_PLACE_LIST',
  SET_PLACE_LIST: 'SET_PLACE_LIST',
  SET_PLACES_LISTENER: 'SET_PLACES_LISTENER',
  UPDATE_PLACE_TYPES: 'UPDATE_PLACE_TYPES',
  SET_PLACE_TYPES_LIST: 'SET_PLACE_TYPES_LIST',
  SET_PLACE_TYPES_LISTENER: 'SET_PLACE_TYPES_LISTENER'
};

export const Quest = {
  DELETING_QUEST: 'DELETING_QUEST',
  CREATING_QUEST: 'CREATING_QUEST',
  UPDATE_QUEST: 'UPDATE_QUEST',
  UPDATE_QUEST_LIST: 'UPDATE_QUEST_LIST',
  SET_QUEST_LIST: 'SET_QUEST_LIST',
  SET_QUESTS_LISTENER: 'SET_QUESTS_LISTENER'
};

export const Event = {
  UPDATE_EVENT_LIST: 'UPDATE_EVENT_LIST',
  SET_EVENTS_LISTENER: 'SET_EVENTS_LISTENER'
};

export const Npc = {
  DELETING_NPC: 'DELETING_NPC',
  CREATING_NPC: 'CREATING_NPC',
  UPDATE_NPC: 'UPDATE_NPC',
  UPDATE_NPC_LIST: 'UPDATE_NPC_LIST',
  SET_NPC_LIST: 'SET_NPC_LIST',
  SET_NPCS_LISTENER: 'SET_NPCS_LISTENER'
};

export const Tag = {
  UPDATE_TAG_LIST: 'UPDATE_TAG_LIST',
  SET_TAGS_LISTENER: 'SET_TAGS_LISTENER'
};

export const Floor = {
  UPDATE_FLOOR_LIST: 'UPDATE_FLOOR_LIST',
  DELETING_FLOOR: 'DELETING_FLOOR',
  SET_FLOORS_LISTENER: 'SET_FLOORS_LISTENER'
};

export const Note = {
  UPDATING_NOTE: 'UPDATING_NOTE',
  DELETING_NOTE: 'DELETING_NOTE',
  CREATING_NOTE: 'CREATING_NOTE',
  UPDATE_NOTE_LIST: 'UPDATE_NOTE_LIST',
  SET_NOTES_LISTENER: 'SET_NOTES_LISTENER'
};

export const Tile = {
  UPDATING_TILE: 'UPDATING_TILE',
  DELETING_TILE: 'DELETING_TILE',
  CREATING_TILE: 'CREATING_TILE',
  UPDATE_TILE_LIST: 'UPDATE_TILE_LIST',
  SET_TILES_LISTENER: 'SET_TILES_LISTENER'
};

export const Value = {
  UPDATING_VALUE: 'UPDATING_VALUE',
  DELETING_VALUE: 'DELETING_VALUE',
  CREATING_VALUE: 'CREATING_VALUE',
  SET_VALUES_LIST: 'SET_VALUES_LIST',
  UPDATE_VALUE_LIST: 'UPDATE_VALUE_LIST',
  SET_VALUES_LISTENER: 'SET_VALUES_LISTENER'
};

export const Alignment = {
  UPDATING_ALIGNMENT: 'UPDATING_ALIGNMENT',
  DELETING_ALIGNMENT: 'DELETING_ALIGNMENT',
  CREATING_ALIGNMENT: 'CREATING_ALIGNMENT',
  SET_ALIGNMENTS_LIST: 'SET_ALIGNMENTS_LIST',
  UPDATE_ALIGNMENT_LIST: 'UPDATE_ALIGNMENT_LIST',
  SET_ALIGNMENTS_LISTENER: 'SET_ALIGNMENTS_LISTENER'
};

export const Quirk = {
  UPDATING_QUIRK: 'UPDATING_QUIRK',
  DELETING_QUIRK: 'DELETING_QUIRK',
  CREATING_QUIRK: 'CREATING_QUIRK',
  SET_QUIRKS_LIST: 'SET_QUIRKS_LIST',
  UPDATE_QUIRK_LIST: 'UPDATE_QUIRK_LIST',
  SET_QUIRKS_LISTENER: 'SET_QUIRKS_LISTENER'
};

export const Occupation = {
  UPDATING_OCCUPATION: 'UPDATING_OCCUPATION',
  DELETING_OCCUPATION: 'DELETING_OCCUPATION',
  CREATING_OCCUPATION: 'CREATING_OCCUPATION',
  SET_OCCUPATIONS_LIST: 'SET_OCCUPATIONS_LIST',
  UPDATE_OCCUPATION_LIST: 'UPDATE_OCCUPATION_LIST',
  SET_OCCUPATIONS_LISTENER: 'SET_OCCUPATIONS_LISTENER'
};

export const Race = {
  UPDATING_RACE: 'UPDATING_RACE',
  DELETING_RACE: 'DELETING_RACE',
  CREATING_RACE: 'CREATING_RACE',
  SET_RACES_LIST: 'SET_RACES_LIST',
  UPDATE_RACE_LIST: 'UPDATE_RACE_LIST',
  SET_RACES_LISTENER: 'SET_RACES_LISTENER'
};

export const Gender = {
  UPDATING_GENDER: 'UPDATING_GENDER',
  DELETING_GENDER: 'DELETING_GENDER',
  CREATING_GENDER: 'CREATING_GENDER',
  SET_GENDERS_LIST: 'SET_GENDERS_LIST',
  UPDATE_GENDER_LIST: 'UPDATE_GENDER_LIST',
  SET_GENDERS_LISTENER: 'SET_GENDERS_LISTENER'
};
