export const Login = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER'
};

export const Campaign = {
  SET_CURRENT_CAMPAIGN: 'SET_CURRENT_CAMPAIGN',
  UPDATE_CAMPAIGN_LIST: 'UPDATE_CAMPAIGN_LIST',
  CREATING_CAMPAIGN: 'CREATING_CAMPAIGN',
  SET_CAMPAIGN_LIST: 'SET_CAMPAIGN_LIST',
  DELETING_CAMPAIGN: 'DELETING_CAMPAIGN'
};

export const Place = {
  DELETING_PLACE: 'DELETING_PLACE',
  CREATING_PLACE: 'CREATING_PLACE',
  UPDATE_PLACE_LIST: 'UPDATE_PLACE_LIST',
  SET_PLACE_LIST: 'SET_PLACE_LIST',
  SET_PLACES_LISTENER: 'SET_PLACES_LISTENER',
  UPDATE_PLACE_TYPES: 'UPDATE_PLACE_TYPES',
  SET_PLACE_TYPES_LISTENER: 'SET_PLACE_TYPES_LISTENER'
};

export const Quest = {
  UPDATE_QUEST_LIST: 'UPDATE_QUEST_LIST',
  SET_QUESTS_LISTENER: 'SET_QUESTS_LISTENER'
};

export const Npc = {
  UPDATE_NPC_LIST: 'UPDATE_NPC_LIST',
  SET_NPCS_LISTENER: 'SET_NPCS_LISTENER'
};


export const Tag = {
  UPDATE_TAG_LIST: 'UPDATE_TAG_LIST',
  SET_TAGS_LISTENER: 'SET_TAGS_LISTENER'
};
